Repository UBC-MDS/DSCI-532_2025_15_RetailPulse, pull requests merged in 2025-03, with the labels that each got.

#37 This commit is fixing issues for deployment
  environment.yaml
  notebooks/explore.ipynb
  requirements.txt
Labels: bug

#39 This commit will fix the import statements
  src/app.py
Labels: bug

#41 File fixing deployment
  src/app.py
Labels: bug

#44 This commit will create a sample file which will help DB to render on…
  data/processed/sample.csv
  src/data/data.py
Labels: bug

#45 Summary metrics on top
  src/app.py
  src/callbacks/__init__.py
  src/components/__init__.py
  src/components/summary_metrics.py
  src/data/__init__.py
  src/data/data.py
Labels: enhancement

#47 Bar chart for quantity sold
  data/processed/sample.csv
  src/app.py
  src/callbacks/charts.py
  src/components/monthly_sales_card.py
  src/data/data.py
Labels: enhancement

#50 This commit will improve some sections of reflections
  reports/m2_reflection.md
Labels: documentation

#51 Style changes
  src/app.py
  src/callbacks/charts.py
  src/components/customer_retention_card.py
  src/components/dhruv_card.py
  src/components/footer.py
  src/components/header.py
  src/components/monthly_sales_card.py
  src/components/revenue_trends_card.py
  src/data/data.py
Labels: enhancement, feature

#75 Sidebar + Addressing Joel's Minor Feedback
  notebooks/explore.ipynb
  src/app.py
  src/assets/widgets.css
  src/callbacks/charts.py
  src/components/customer_retention_card.py
  src/components/footer.py
  src/components/general.py
  src/components/header.py
  src/components/map_card.py
  src/components/monthly_sales_card.py
  src/components/product_revenue_card.py
  src/components/revenue_trends_card.py
  src/components/sidebar.py
  src/components/summary_metrics.py
  src/components/widgets.py
  src/data/data.py
Labels: enhancement, feature

#76 Sidebar
  src/assets/footer.css
  src/assets/graphs.css
  src/assets/header.css
  src/assets/sidebar.css
  src/assets/summary.css
  src/assets/widgets.css
  src/callbacks/charts.py
  src/components/customer_retention_card.py
  src/components/footer.py
  src/components/header.py
  src/components/map_card.py
  src/components/monthly_sales_card.py
  src/components/product_revenue_card.py
  src/components/revenue_trends_card.py
  src/components/sidebar.py
  src/components/summary_metrics.py
  src/components/widgets.py
Labels: enhancement

#78 Country and category filters, plus a favicon
  src/assets/favicon.ico
  src/callbacks/charts.py
  src/data/data.py
Labels: enhancement, feature

#80 This commit will add the filter capability for summary stats
  src/callbacks/charts.py
  src/components/widgets.py
  src/data/data.py
Labels: enhancement

#83 Adding multiple dropdown
  src/callbacks/charts.py
  src/components/widgets.py
  src/data/data.py
Labels: enhancement

#87 set up reflection for milestone 3
  reports/m3_reflection.md
Labels: documentation

#89 Updated demo GIF
  README.md
  img/m3.gif
Labels: documentation

#90 Ms-4 peer-review
  src/app.py
  src/assets/graphs.css
  src/assets/summary.css
  src/callbacks/charts.py
  src/callbacks/summary_metric_helper.py
  src/components/map_card.py
  src/components/summary_metrics.py
  src/data/data.py
Labels: enhancement

#97 added tab tittle and favicon
  src/app.py
  src/assets/favicon.ico
Labels: documentation, enhancement

#98 Docstrings
  notebooks/explore.ipynb
  src/callbacks/charts.py
  src/callbacks/summary_metric_helper.py
  src/data/data.py
Labels: documentation, enhancement, good first issue

#100 This set of commits is increasing the sample size, update the data file to parquet, update the environment file, requirement file
  data/processed/processed_parquet.parquet
  data/processed/sample.csv
  environment.yaml
  notebooks/data_fixer.ipynb
  requirements.txt
  src/data/data.py
Labels: enhancement

#104 Docstring + Test + Joel's MS4 minor Feedback
  requirements.txt
  src/__init__.py
  src/assets/summary.css
  src/assets/widgets.css
  src/callbacks/__init__.py
  src/callbacks/charts.py
  src/callbacks/summary_metric_helper.py
  tests/callback_test.py
  tests/test_data_functions.py
Labels: documentation, enhancement, good first issue, feature

#107 Caching
  environment.yaml
  src/app.py
  src/data/data.py
Labels: enhancement

#109 quick fix in readme
  README.md
Labels: documentation
